# Generated by Django 5.0.7 on 2024-10-10 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='two_d_cover',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='two_d_cover',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
