# Generated by Django 5.0.7 on 2024-10-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover_one', '0002_two_d_cover_created_at_two_d_cover_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='two_d_cover',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='two_d_cover',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
